FROM node:24-trixie

WORKDIR /app

RUN curl -fsSL https://tailscale.com/install.sh | sh

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml .npmrc ./
COPY ui/package.json ./ui/package.json
COPY patches ./patches
COPY scripts ./scripts

RUN corepack enable
RUN pnpm install --frozen-lockfile

COPY . .
RUN OPENCLAW_A2UI_SKIP_MISSING=1 pnpm build
RUN pnpm ui:install
RUN pnpm ui:build

ENV NODE_ENV=production
EXPOSE 18789
ENTRYPOINT ["./entrypoint.sh"]
